// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pmcrr.DataContext;

namespace pmcrr.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181020080803_outfit, wearing, user table")]
    partial class outfitwearingusertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pmcrr.Models.Outfit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("purpose");

                    b.HasKey("id");

                    b.ToTable("Outfit");
                });

            modelBuilder.Entity("pmcrr.Models.OutfitAndWearing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("outfitid");

                    b.Property<int?>("wearingid");

                    b.HasKey("id");

                    b.HasIndex("outfitid");

                    b.HasIndex("wearingid");

                    b.ToTable("OutfitAndWearing");
                });

            modelBuilder.Entity("pmcrr.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("pmcrr.Models.Wearing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("category");

                    b.Property<int>("ownerId");

                    b.HasKey("id");

                    b.ToTable("Wearing");
                });

            modelBuilder.Entity("pmcrr.Models.OutfitAndWearing", b =>
                {
                    b.HasOne("pmcrr.Models.Outfit", "outfit")
                        .WithMany()
                        .HasForeignKey("outfitid");

                    b.HasOne("pmcrr.Models.Wearing", "wearing")
                        .WithMany()
                        .HasForeignKey("wearingid");
                });
#pragma warning restore 612, 618
        }
    }
}
